<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('contact', array('action' => 'add')));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'contact-add');
$form->setAttribute('class', 'clearfix');
$form->setAttribute('role', 'form');
$formLabel = $this->plugin('formLabel');
$formLabelAttributes = array('class' => 'control-label full-width');
?>

<h1 class="page-header text-center"><?php echo $this->escapeHtml('Új cím'); ?></h1>

<?php echo $this->form()->openTag($form); ?>
    <div class="form-group col-sm-offset-3 col-sm-6">
        <?php
        $contact_name = $form->get('contact_name');
        echo $formLabel($contact_name);
        echo $this->formInput($contact_name);
        echo $this->formElementErrors($contact_name);
        ?>
    </div>
    <div class="form-group col-sm-offset-3 col-sm-6">
        <?php
        $contact_email = $form->get('contact_email');
        echo $formLabel($contact_email);
        echo $this->formInput($contact_email);
        echo $this->formElementErrors($contact_email);
        ?>
    </div>
    <div class="form-group col-sm-offset-3 col-sm-6">
        <?php
        $contact_cell = $form->get('contact_cell');
        echo $formLabel($contact_cell);
        echo $this->formInput($contact_cell);
        echo $this->formElementErrors($contact_cell);
        ?>
    </div>
    <div class="form-group col-sm-offset-3 col-sm-6">
        <?php
        $categories = $form->get('categories');
        $categories->setValueOptions($categoryValues);
        echo $formLabel($categories);
        echo $this->formSelect($categories);
        echo $this->formElementErrors($categories);
        ?>
    </div>
    <?php echo $this->formInput($form->get('security')) ?>
    <div class="form-group col-sm-offset-3 col-sm-6 text-center">
        <?php echo $this->formButton($form->get('add')) ?>
    </div>
<?php echo $this->form()->closeTag($form); ?>
