<h1 class="page-header text-center"><?php echo $this->escapeHtml('Címek'); ?></h1>

<div class="table-responsive">
<table class="table table-striped">
    <tr>
        <th><?php echo $this->translate('Név'); ?></th>
        <th><?php echo $this->translate('E-mail'); ?></th>
        <th><?php echo $this->translate('Telefon'); ?></th>
        <th><?php echo $this->translate('Kategória'); ?></th>
        <th><?php echo $this->translate('Felvéve'); ?></th>
        <th><?php echo $this->translate('Művelet'); ?></th>
    </tr>
    <?php if (!empty($contacts)) : ?>
    <?php foreach ($contacts as $contact) : ?>
        <tr>
            <td><strong><?php echo $this->escapeHtml($contact->contact_name);?></strong></td>
            <td><?php echo $this->escapeHtml($contact->contact_email);?></strong></td>
            <td><?php echo $this->escapeHtml($contact->contact_cell);?></td>
            <td><?php echo $this->escapeHtml($contact->contact_categories);?></td>
            <td><?php echo $this->escapeHtml($contact->contact_add_date);?></td>
            <td class="col-other">
                <div class="btn-group" action="group" aria-label="...">
                    <a href="<?php echo $this->url('contact', array('action' => 'edit', 'id' => $contact->id)); ?>" action="button" class="btn btn-default btn-sm"><span class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></span></a>
                    <a href="<?php echo $this->url('contact', array('contact' => 'del', 'id' => $contact->id)); ?>" action="button" class="btn btn-default btn-sm confirm-del"><span class="fa fa-trash-o fa-lg"></span></a>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    <?php else : ?>
        <tr>
            <td colspan="6" class="text-center">Jelenleg üres a címjegyzék.</td>
        </tr>
    <?php endif; ?>
</table>
</div>
