<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Címjegyzék'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->appendStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->appendStylesheet($this->basePath() . '/css/formValidation.min.css')
                        ->appendStylesheet($this->basePath() . '/css/select2.css')
                        ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')
                        ->appendStylesheet($this->basePath() . '/css/style.css')?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('contact') ?>"><span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span> <?php echo $this->translate('Címjegyzék') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><?php echo $this->translate('Cím'); ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('contact', array('action' => 'add')); ?>"><?php echo $this->translate('Új cím'); ?></a></li>
                                <li><a href="<?php echo $this->url('contact', array('action' => 'list')); ?>"><?php echo $this->translate('Címlista'); ?></a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2015. Balogh Péter. <?php echo $this->translate('Minden jog fenntartva.') ?></p>
            </footer>
        </div> <!-- /container -->

        <script src="<?php echo $this->basePath() . '/js/jquery-1.10.2.min.js' ?>"></script>
        <script src="<?php echo $this->basePath() . '/js/bootstrap.min.js' ?>"></script>
        <script src="<?php echo $this->basePath() . '/js/formValidation.min.js' ?>"></script>
        <script src="<?php echo $this->basePath() . '/js/formValidation.bootstrap.min.js' ?>"></script>
        <script src="<?php echo $this->basePath() . '/js/language/formValidation_hu_HU.js' ?>"></script>
        <script src="<?php echo $this->basePath() . '/js/bootstrap-confirmation.min.js' ?>"></script>
        <script src="<?php echo $this->basePath() . '/js/select2.min.js' ?>"></script>
        <script src="<?php echo $this->basePath() . '/js/language/select2_hu_HU.js' ?>"></script>
        <?php echo $this->inlineScript()."\n"; ?>
        <script src="<?php echo $this->basePath() . '/js/custom.js' ?>"></script>
    </body>
</html>
